version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: assessment-mongodb
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - assessment_mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: assessment-mongo-ui
    restart: no
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb

volumes:
  assessment_mongo_data: